name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Replace BasePath
        run: |
          sed -i 's/__CICD_BASE_PATH__/\/pr-${{ github.event.pull_request.number }}/g' evidence.config.yaml
          cat evidence.config.yaml
      - name: Build
        env:
          EVIDENCE_BUILD_DIR: './build/${{ github.event.repository.name }}'
        run: |
          npm run sources
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Copy to S3
        run: |
          aws s3 cp --recursive ./build/${{ github.event.repository.name }} s3://evidence-delivery-bucket/pr-${{ github.event.pull_request.number }}

  cleanup:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Delete S3 objects
        run: |
          aws s3 rm --recursive s3://evidence-delivery-bucket/pr-${{ github.event.pull_request.number }}
