name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          EVIDENCE_BUILD_DIR: 'build/pr-${{ github.event.pull_request.number }}'
        run: |
          npm run sources
          npm run build

      - name: Checkout to gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Deploy to gh-pages with PR folders
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          mkdir -p pr-${{ github.event.pull_request.number }}
          rm -rf pr-${{ github.event.pull_request.number }}/*
          echo "Copying build to pr-${{ github.event.pull_request.number }}"
          cp -r build/* pr-${{ github.event.pull_request.number }}/
          git status
          git add pr-${{ github.event.pull_request.number }}
          git status
          git commit -m "Deploy PR-${{ github.event.pull_request.number }} to GitHub Pages"
          git push origin gh-pages
