name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: build
        env:
          BASE_PATH: '/pr-${{ github.event.pull_request.number }}'
          EVIDENCE_BUILD_DIR: './build/${{ github.event.repository.name }}'
        run: |
          npm run sources
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Copy to S3
        run: |
          aws s3 cp --recursive ./build/${{ github.event.repository.name }} s3://evidence-delivery-bucket/pr-${{ github.event.pull_request.number }}
